### ISSUE TITLE
Blendigo doesn't seem to work for blender 4.1 and above

### ISSUE THREAD

**Issue by Eneen** [glaretechnologies/blendigo#38]
Quick snippet from console, blender 4.2:

```
[Indigo 2024-Jul-03 08:35:09] ERROR: 'Mesh' object has no attribute 'calc_normals_split'
Traceback (most recent call last):
  File "C:\Users\Olo\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\indigo_exporter\operators\__init__.py", line 287, in execute
    geometry_exporter.iterateScene(depsgraph)
  File "C:\Users\Olo\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\indigo_exporter\export\__init__.py", line 161, in iterateScene
    self.handleMesh(ob_inst)
  File "C:\Users\Olo\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\indigo_exporter\export\geometry.py", line 336, in handleMesh
    self.buildMesh(obj),
    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olo\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\indigo_exporter\export\geometry.py", line 345, in buildMesh
    return self.exportMeshElement(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olo\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\indigo_exporter\export\geometry.py", line 451, in exportMeshElement
    (used_mat_indices, use_shading_normals) = igmesh_writer.factory(self.scene, obj, full_mesh_path, mesh, debug=OBJECT_ANALYSIS)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olo\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\indigo_exporter\export\igmesh.py", line 74, in factory
    (used_mat_indices, use_shading_normals) = igmesh_writer.write_mesh(filename, scene, obj, mesh)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Olo\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\indigo_exporter\export\igmesh.py", line 100, in write_mesh
    mesh.calc_normals_split()
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Mesh' object has no attribute 'calc_normals_split
```

**Comment by TrippyLighting** [comment]
The Blender API has changed again with 4.1:
[See here.](https://developer.blender.org/docs/release_notes/4.1/python_api/)

"create_normals_split, calc_normals_split, and free_normals_split are removed, and are replaced by the simpler Mesh.corner_normals collection property. Since it gives access to the normals cache, it is automatically updated when relevant data changes."

I believe in igmesh.py, the line "mesh.calc_normals_split()" can simply be commented out.

**Comment by Ono-Sendai** [comment]
Should be fixed now.
